### ISSUE TITLE
Tags template wrongly use posts instead of tag_posts

### ISSUE THREAD

**Issue by hnlocher** [jbake-org/jbake-example-project-thymeleaf#8]
Two occurences : 

* [line 15](https://github.com/jbake-org/jbake-example-project-thymeleaf/blob/a62ca9f78005dd7ce620f0df773f74a09961e6e2/templates/tags.thyme#L15)
* [line 24](https://github.com/jbake-org/jbake-example-project-thymeleaf/blob/a62ca9f78005dd7ce620f0df773f74a09961e6e2/templates/tags.thyme#L24)

Proposed correction : 
* [correct_tagsindex2.patch](https://github.com/jbake-org/jbake-example-project-thymeleaf/files/10330735/correct_tagsindex2.patch)

**Comment by jonbullock** [comment]
Thanks for raising this @hnlocher
